### ISSUE TITLE
&符在``` ```下显示为>

### ISSUE THREAD

**Issue by HarryChen0506** [hangxingliu/mdjs#2]
例如
``` 
function （） {
  true&&1234
}
```
显示为
function （） {
  true>>1234
}

**Comment by hangxingliu** [comment]
最新的commit中修复了

**Comment by HarryChen0506** [comment]
你写的这个库真的好棒啊，解决了我们写markdown转html的需求，在此感谢。

**Comment by hangxingliu** [comment]
@HarryChen0506 如果有啥问题页欢迎到这儿提Issue或Pull Request
